title: Design Patterns
description: Documentation and examples for common design patterns implemented in Python.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

mermaid:
  version: "10.9.0"

url: https://justmatias.github.io
baseurl: /design-patterns-explained

aux_links:
  'Repository':
    - 'https://github.com/justmatias/design-patterns-explained'
  'GitHub':
    - 'https://github.com/justmatias'
  'LinkedIn':
    - 'https://www.linkedin.com/in/matiagimenez'

nav_sort: order

exclude:
  - README.md
  - CONTRIBUTING.md
  - docs/
