title: Design Patterns in Python
description: Documentation and examples for common design patterns implemented in Python.
remote_theme: just-the-docs/just-the-docs

url: https://justmatias.github.io
baseurl: /design-patterns-explained

aux_links:
  "GitHub":
    - "https://github.com/justmatias/design-patterns-explained"

nav_sort: order

exclude:
  - README.md
